### ISSUE TITLE
Ongoing Update Community Principles Issue

### ISSUE THREAD

**Issue by andytudhope** [LinumLabs/ReactMeetup#1]
There is a Principles.md file in this repo that is intended as a living document for the community. I will issue ongoing rewards in Ether for updates to it from anyone in the world.

All you need to do is sign up at openbounty.status.im, update your Ethereum address in the Payment Details section and then submit a Pull Request with your changes to the Principles file.

It's alive!!

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xe85fb25c331d477632e34c51c5e3f7ca633e23f7ece2d1fdfc3e6c368541f397](https://etherscan.io/tx/0xe85fb25c331d477632e34c51c5e3f7ca633e23f7ece2d1fdfc3e6c368541f397)

**Comment by arash009** [comment]
Hey @andytudhope so I'm trying to update my current Ethereum address on the 'My Payment Detail' but looks like you cant edit once you have added one in. That cant be right?
Shall we log a bounty for someone to fix that ;-)

**Comment by cf2013** [comment]
I'm not sure what is the purpose of this bounty, would you explain?, my transaction hash is: https://etherscan.io/tx/0x8bd42fced50e4d513852cbdc7698598c8c34fb52b0abeef826161779df943f54

**Comment by cryptowanderer** [comment]
@arash009 log in to opnbounty.status.im in an incognito window, or with MetaMask or the parity extension disabled and you should be able to edit - otherwise it'll auto-pickup your adress.

@cf2013 you have sent ETH to the contract - 0.00004 it seems like. The contract will only pay out to the person who submits a pull request that fixes the issue and references the issue number. So, much as I'd like to, I can't return it to you. You can find out how this actually works here: https://wiki.status.im/Status_Open_Bounty
